# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{big_cms}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tony Stubblebine"]
  s.date = %q{2010-11-22}
  s.email = %q{tony+bigcms@tonystubblebine.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README",
    "README.rdoc"
  ]
  s.files = [
    "app/controllers/application_controller.rb",
    "app/controllers/components_controller.rb",
    "app/controllers/content_managers_controller.rb",
    "app/controllers/navigations_controller.rb",
    "app/controllers/pages_controller.rb",
    "app/helpers/components_helper.rb",
    "app/helpers/content_managers_helper.rb",
    "app/helpers/navigations_helper.rb",
    "app/helpers/pages_helper.rb",
    "app/models/component.rb",
    "app/models/content_manager.rb",
    "app/models/navigation.rb",
    "app/models/page.rb",
    "app/views/components/_form.html.erb",
    "app/views/components/edit.html.erb",
    "app/views/components/index.html.erb",
    "app/views/components/new.html.erb",
    "app/views/components/show.html.erb",
    "app/views/content_managers/_form.html.erb",
    "app/views/content_managers/edit.html.erb",
    "app/views/content_managers/index.html.erb",
    "app/views/content_managers/new.html.erb",
    "app/views/content_managers/show.html.erb",
    "app/views/navigations/_form.html.erb",
    "app/views/navigations/edit.html.erb",
    "app/views/navigations/index.html.erb",
    "app/views/navigations/new.html.erb",
    "app/views/navigations/show.html.erb",
    "app/views/pages/_form.html.erb",
    "app/views/pages/edit.html.erb",
    "app/views/pages/index.html.erb",
    "app/views/pages/new.html.erb",
    "app/views/pages/show.html.erb",
    "config/application.rb",
    "config/boot.rb",
    "config/database.yml",
    "config/environment.rb",
    "config/environments/development.rb",
    "config/environments/production.rb",
    "config/environments/test.rb",
    "config/initializers/backtrace_silencers.rb",
    "config/initializers/inflections.rb",
    "config/initializers/mime_types.rb",
    "config/initializers/secret_token.rb",
    "config/initializers/session_store.rb",
    "config/locales/en.yml",
    "config/routes.rb",
    "lib/big_cms.rb",
    "lib/big_cms/engine.rb",
    "lib/big_cms/railties/tasks.rake",
    "lib/generators/big_cms/big_cms_generator.rb",
    "lib/generators/big_cms/templates/create_components_migration.rb",
    "lib/generators/big_cms/templates/create_content_managers.rb",
    "lib/generators/big_cms/templates/create_navigations_migration.rb",
    "lib/generators/big_cms/templates/create_pages_migration.rb"
  ]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Rails engine for handling content management.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["> 3.0.0"])
      s.add_runtime_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<rails>, ["> 3.0.0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, ["> 3.0.0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

